# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016' #'ubuntu-latest'
  demands:
  - npm

variables:
  wwwRootDir: 'src/eacuna'
  sourceFolder: 'dist'

steps:
- task: NodeTool@0
  displayName: 'Install Node.JS'
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

# Install ParcelJS for CI
- script: npm install parcel-bundler --save-dev
  displayName: 'Install parceljs'

- script: npm run build
  displayName: 'Run npm build'
  workingDirectory: '$(wwwRootDir)'

- script: npm pack
  displayName: 'Package for npm release'

- task: CopyFiles@2
  displayName: 'Copy output files'
  inputs:
    SourceFolder: '$(sourceFolder)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish output files'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'eacuna'
    publishLocation: 'Container'
